### ISSUE TITLE
Standard shader broken in Unity 5.5.0b4

### ISSUE THREAD

**Issue by grenappels** [Looking-Glass/HypercubeUnitySource#2]
Getting this error:
Shader error in 'Hypercube/Standard': invalid subscript 'ndotl' at Assets/Hypercube/internal/materials/S_HypercubeStandardCore.cginc(51) (on d3d11)

Compiling Vertex program with DIRECTIONAL
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING SHADER_API_DESKTOP

**Comment by enjrolas** [comment]
Yeah, try going back to unity 5.4.x for now (tested on 5.4.3)

Dez is preparing the next version of unity, which has fixes for 5.5.x, but isn’t ready for release yet (coming in a week or so)

—me


On February 7, 2017 at 2:37:12 PM, Kyle Appelgate (notifications@github.com) wrote:

Getting this error:
Shader error in 'Hypercube/Standard': invalid subscript 'ndotl' at Assets/Hypercube/internal/materials/S_HypercubeStandardCore.cginc(51) (on d3d11)

Compiling Vertex program with DIRECTIONAL
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING SHADER_API_DESKTOP

**Comment by Dezt** [comment]
should be fixed now
